name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sayantan181222
          outputs: |
            dist/github-snake-light.svg?color_snake=#8a2be2&color_dots=#ebedf0,#d1c4e9,#b39ddb,#9575cd,#7e57c2
            dist/github-snake-dark.svg?color_snake=#00ffff&color_dots=#0d1117,#1f1a3a,#3d1e6d,#800080,#b800e6

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
